/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlurCard: typeof import('./src/components/BlurCard.vue')['default']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElText: typeof import('element-plus/es')['ElText']
    IconLink: typeof import('./src/components/IconLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spacer: typeof import('./src/components/Spacer.vue')['default']
  }
}
